

# Dataset
root: /home/takuya/workspace/datasets/working_dataset
video_dir: images
output_dir: output

# Model ()
model: resnet18


#Dataloader setting
batch_size: 32
image_size: 224
num_workers: 2










